"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { friendlyErrorMessage } from "@/lib/toast-error";
import { logActivity, type ActivityType } from "@/app/actions/leads";

const TYPES: { value: ActivityType; label: string }[] = [
  { value: "note", label: "Note" },
  { value: "call", label: "Call" },
  { value: "whatsapp_sent", label: "WhatsApp sent" },
  { value: "whatsapp_received", label: "WhatsApp received" },
  { value: "meeting", label: "Meeting" },
  { value: "demo", label: "Demo" },
  { value: "quote_sent", label: "Quote sent" },
];

export function ActivityForm({ leadId }: { leadId: string }) {
  const router = useRouter();
  const { toast } = useToast();
  const [type, setType] = useState<ActivityType>("note");
  const [note, setNote] = useState("");
  const [isPending, startTransition] = useTransition();

  // Every selectable activity in this form is human-typed — none of them
  // is `status_change` (which is auto-generated by the server when the
  // user uses the Change Status dialog). So a non-empty note is required
  // for every submission.
  const canSubmit = note.trim().length > 0 && !isPending;

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!note.trim()) {
      toast({
        title: "Please add a short note for this activity",
        variant: "destructive",
      });
      return;
    }
    startTransition(async () => {
      try {
        await logActivity(leadId, type, note);
        toast({ title: "Activity logged" });
        setNote("");
        setType("note");
        router.refresh();
      } catch (err) {
        toast({
          title: "Could not save",
          description: friendlyErrorMessage(err),
          variant: "destructive",
        });
      }
    });
  }

  return (
    <form
      onSubmit={submit}
      className="card-soft space-y-3 border border-border"
    >
      <div className="grid grid-cols-1 sm:grid-cols-[180px_1fr] gap-3">
        <div className="space-y-1.5">
          <Label className="text-sm">Type</Label>
          <Select value={type} onValueChange={(v) => setType(v as ActivityType)}>
            <SelectTrigger className="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {TYPES.map((t) => (
                <SelectItem key={t.value} value={t.value}>
                  {t.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="activity_note" className="text-sm">Note</Label>
          <Textarea
            id="activity_note"
            rows={2}
            placeholder="What happened?"
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
        </div>
      </div>
      <div className="flex justify-end">
        <Button type="submit" disabled={!canSubmit} className="h-11">
          {isPending ? "Saving..." : "Save activity"}
        </Button>
      </div>
    </form>
  );
}
